import { SlideshowConfig } from "@/lib/types";
import { speakers } from "@/lib/speakers";
import {
  BaselinesSlide,
  BuildBigThenPruneSlide,
  CalibrationObjectiveSlide,
  ExperimentDesignSlide,
  FutureWorkSlide,
  GeneralizationSlide,
  GeographyAccuracySlide,
  L0MathSlide,
  LedgerSlide,
  LouizosFoundationSlide,
  OperabilitySlide,
  PipelineSlide,
  PolicyGoalSlide,
  PopulaceValueSlide,
  QuestionsSlide,
  RepresentativenessSlide,
  ResultsArcBaselinesSlide,
  ResultsArcL0Slide,
  ResultsArcRefitSlide,
  ResultsArcScaledSlide,
  RoadmapSlide,
  SamplingQuestionSlide,
  TakeawaySlide,
  TitleSlide,
  TranslationSlide,
  WeightLayoutBothSlide,
  WeightLayoutWideSlide,
} from "./slides";

export const l0Ima2026Config: SlideshowConfig = {
  id: "l0-ima-2026",
  title: "L0 regularization for subnational microsimulation calibration",
  description:
    "PolicyEngine IMA 2026 deck on using L0 regularization to prune a full Populace candidate microdataset while preserving calibration fit.",
  date: "2026-07-01",
  location: "IMA 2026, Brussels",
  footerText: "IMA 2026 · L0 regularization",
  speakers: [speakers["maria-juaristi"]],
  slides: [
    TitleSlide,
    RoadmapSlide,
    PolicyGoalSlide,
    WeightLayoutWideSlide,
    WeightLayoutBothSlide,
    BuildBigThenPruneSlide,
    LedgerSlide,
    PopulaceValueSlide,
    PipelineSlide,
    RepresentativenessSlide,
    SamplingQuestionSlide,
    BaselinesSlide,
    CalibrationObjectiveSlide,
    LouizosFoundationSlide,
    TranslationSlide,
    L0MathSlide,
    ExperimentDesignSlide,
    ResultsArcBaselinesSlide,
    ResultsArcScaledSlide,
    ResultsArcL0Slide,
    ResultsArcRefitSlide,
    GeographyAccuracySlide,
    GeneralizationSlide,
    OperabilitySlide,
    FutureWorkSlide,
    TakeawaySlide,
    QuestionsSlide,
  ],
};
