import { SlideshowConfig } from "@/lib/types";
import { speakers } from "@/lib/speakers";
import {
  BaselinesSlide,
  BuildBigThenPruneSlide,
  CalibrationObjectiveSlide,
  ExperimentDesignSlide,
  FutureWorkSlide,
  GeographyAccuracySlide,
  L0ArmsSlide,
  L0MathSlide,
  LedgerSlide,
  LouizosFoundationSlide,
  OperabilitySlide,
  PipelineSlide,
  PlatformFutureWorkSlide,
  PolicyGoalSlide,
  PopulaceValueSlide,
  QuestionsSlide,
  RepresentativenessSlide,
  ResultsArcBaselinesSlide,
  ResultsArcL0Slide,
  ResultsArcRefitSlide,
  ResultsArcScaledSlide,
  RoadmapSlide,
  SamplingQuestionSlide,
  SectionCalibrationSlide,
  SectionL0Slide,
  SectionModelSlide,
  SectionNextStepsSlide,
  SectionPruningSlide,
  SectionSupportSlide,
  TakeawaySlide,
  TitleSlide,
  WeightLayoutBothSlide,
  WeightLayoutWideSlide,
} from "./slides";

export const l0Ima2026Config: SlideshowConfig = {
  id: "l0-ima-2026",
  title: "L0 regularization for subnational microsimulation calibration",
  description:
    "PolicyEngine IMA 2026 deck on using L0 regularization to prune a full Populace candidate microdataset while preserving calibration fit.",
  date: "2026-07-01",
  location: "IMA 2026, Brussels",
  footerText: "IMA 2026 · L0 regularization",
  speakers: [speakers["maria-juaristi"]],
  slides: [
    TitleSlide,
    RoadmapSlide,
    // § 1 · What PolicyEngine models
    SectionModelSlide,
    PolicyGoalSlide,
    WeightLayoutWideSlide,
    WeightLayoutBothSlide,
    BuildBigThenPruneSlide,
    // § 2 · Constructing the support
    SectionSupportSlide,
    LedgerSlide,
    PopulaceValueSlide,
    PipelineSlide,
    RepresentativenessSlide,
    // § 3 · Calibration
    SectionCalibrationSlide,
    ExperimentDesignSlide,
    CalibrationObjectiveSlide,
    SamplingQuestionSlide,
    // § 4 · Simple pruning methods
    SectionPruningSlide,
    BaselinesSlide,
    ResultsArcBaselinesSlide,
    ResultsArcScaledSlide,
    // § 5 · L0 regularization
    SectionL0Slide,
    L0MathSlide,
    LouizosFoundationSlide,
    L0ArmsSlide,
    ResultsArcL0Slide,
    ResultsArcRefitSlide,
    GeographyAccuracySlide,
    OperabilitySlide,
    // § 6 · Next steps
    SectionNextStepsSlide,
    FutureWorkSlide,
    PlatformFutureWorkSlide,
    TakeawaySlide,
    QuestionsSlide,
  ],
};
