import type { SlideshowConfig } from "@/lib/types";
import {
  AgendaSlide,
  AnalysisSectionSlide,
  Budget2025Slide,
  BudgetDaySlide,
  BudgetSectionSlide,
  ClosingSlide,
  DataSectionSlide,
  EnergyDiscountSlide,
  EnergyWorkSlide,
  PipelineSlide,
  PropertyConceptsSlide,
  PropertyModelSlide,
  PropertySectionSlide,
  ReleaseChecksSlide,
  ResearchSectionSlide,
  TargetsSlide,
  TitleSlide,
  WorkBenefitsSlide,
} from "./slides";

export const scottishGovernment2026Config: SlideshowConfig = {
  id: "scottish-government-2026",
  title: "PolicyEngine: data pipeline, property income and Budget planning",
  description:
    "Follow-up to the February and March meetings: how Microcosm UK builds Scotland's microdata, property income, a targeted energy discount, UK work since April and the Autumn Budget 2026 plan.",
  date: "2026-10-09",
  location: "Scottish Government",
  footerText: "Scottish Government · 9 October 2026",
  slides: [
    TitleSlide,
    AgendaSlide,
    DataSectionSlide,
    PipelineSlide,
    TargetsSlide,
    ReleaseChecksSlide,
    PropertySectionSlide,
    PropertyConceptsSlide,
    PropertyModelSlide,
    AnalysisSectionSlide,
    EnergyDiscountSlide,
    ResearchSectionSlide,
    EnergyWorkSlide,
    WorkBenefitsSlide,
    BudgetSectionSlide,
    Budget2025Slide,
    BudgetDaySlide,
    ClosingSlide,
  ],
};
